spring:
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB
      ## h2 DB
  datasource:
      url: jdbc:h2:~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

      ## MySql DB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: jdbc:mysql://localhost:3306/newttd
#    password: '1234'
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: 'true'
#    hibernate:
#      ddl-auto: create
#    show-sql: 'true'
api:
  naver:
    client_id: yMLNmzMmwJfV81HW82NF
    client_secret: HDdhF9HBBG
  kakao:
    client_id: 389b73fe882b1f88e4efd7b0372ac800

  security:
    oauth2:
      client:
        registration:
          naver:
            scope: name,email
            authorization-grant-type: authorization_code
            client-secret: HDdhF9HBBG
            client-id: yMLNmzMmwJfV81HW82NF
            redirect_uri: http://localhost:8080/login/oauth2/code/naver
            client-name: Naver
          kakao:
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: d08154b0e02a4f165009308850761e36
            scope: profile_nickname,profile_image,account_email
            client-name: Kakao
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth2.0/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  profiles:
    includes: oauth

output:
  ansi:
    enabled:always